exp_name: CTCO
load: False
param:
  dt: 0.1
  discount: 0.98
  z_dim: 1
  actor_NN_gate: Tanh
  actor_NN_nhid: 10
  actor_lr: 0.0001
  actor_opt: Adam
  critic_NN_gate: ReLU
  critic_NN_nhid: 128
  critic_lr: 0.001
  critic_opt: Adam
  beta_NN_gate: Tanh
  beta_NN_nhid: 64
  beta_lr: 0.0001
  beta_opt: Adam
  env: 'Pendulum-v0'
  log_steps: 10000
  max_steps: 250000
  batch_size: 100
param_ID: 0