exp_name: pendulum_tests
param:
  Duraiton_penalty: true
  Duration_penalty_const: 0.02
  Terminaiton_enabled: false
  actor_D_lr: 1.0e-05
  actor_NN_gate: Tanh
  actor_NN_nhid: 10
  actor_beta_lr: 0.0001
  actor_opt: Adam
  actor_z_lr: 4.0e-05
  batch_size: 100
  beta_NN_gate: Tanh
  beta_NN_nhid: 64
  beta_opt: Adam
  critic_NN_gate: ReLU
  critic_NN_nhid: 64
  critic_lr: 0.0001
  critic_opt: Adam
  critic_target_update_tau: 0.01
  discount: 0.98
  dt: 0.1
  env: CT_pendulum
  freez_D: false
  freez_beta: true
  freez_z: false
  load: false
  log_level: 0
  log_steps: 5000
  max_steps: 250000
  save_interval: 10000
  std_depend_on_state: false
  z_dim: 1
param_ID: 0
